<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);

// Wir haben in app/code/g3... eigene Klassen und Funktionen über die wir alle Informationen aus magento aufrufen können
// In der Magento Logik sollte es außerhalb der jeweiligen phtml Dateien geschehen, damit wir von überall auf die Funktionen zugreifen können (Macht ja auch Sinn).
// Schaut euch als Beispiel die helper Klasse vom Nördlichen Schwarzwald mal an oder die Schnittstelle vom Bett, da machen wir das gleiche
// Damit wir drauf zugreifen können, erstellen wir einen "Block", auf gut deutsch wir erstellen ein neues GetProducts Object und können nun seine Funktionen aufrufen
// Das Objekt speichern wir in der Variable $productObj
// Hinweis, wenn ihr weitere Funktionen braucht, die die Produkte betreffen, erweitert genau diese Klasse mit neuen Funktionen, dann könnt ihr immer darauf zurückgreifen
// Wenn ihr was in app/code erweitert oder anpasst müsst ihr meistens in der Console "bin/magento setup:di:compile" laufen lassen bevor ihr es verwenden könnt
$productObj = $block->getLayout()->createBlock('G3\g3core\Block\Html\GetProducts');
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()) :?>
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else :?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
                </a>
            <?php else :?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()) :?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else :?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()) :?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) :?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                <?php else :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                    <?php
                        // Hier rufen wir jetzt die Funktion getConfigChildProductIds aus GetProucts auf und geben die aktuelle Produkt ID mit
                        // Als Ergebnis bekommen wir eine Liste aller verfügbaren Optionen (Varianten) zu dem aktuellen Produkt
                        // Cool, jetzt haben wir eine Liste aller Optionen aber wir brauchen ja genau die, die im Warenkorb liegt
                        // Hinweis, die ganzen Funktionen die ihr in app/code/G3/g3_core findet sind zusammen gegoogelt ;)
                        $childObj = $productObj->getConfigChildProductIds($product->getID());

                        // Wir haben beim Produkt ein Array, dass alle Infos zu den Optionen enthält, yeah! 
                        // außer natürlich die zusatz Attribute vom Wölfel (╯°□°）╯︵ ┻━┻
                        // Also gehen wir das Array mit den Optionsinfos durch und (glücklicherweise) haben die Optionen eine ID, die wir auch bei der Liste $childObj haben 
                        foreach ($_item["qty_options"] as $option) {

                            // Hier gehen wir also die Liste aller Optionen zu dem aktuellen Produkt durch und vergleichen dann die ID'S 
                            foreach ($childObj as $child){     
                                if ($child->getID() === $option['product_id']) {

                                    // Sind die ID's identisch können wir über getData die Zusatzinfo aus sub1de auslesen
                                    // Hier müsst ihr ggf. aufpassen, falls es eine Unterscheidung wie bei den "regulären" Produkten zwischen de und en gibt
                                    // Falls dem so sein sollte schaut in app\design\frontend\g3\mp-theme\Magento_Catalog\templates\product\attributes.phtml rein, 
                                    // da findet ihr ein komplettes Beispiel wie ihr die beiden Sprachversionen unterscheiden und entsprechend Aufrufen könnt
                                    echo '<span class="option_attribute">' . $child->getData('sub1de') . '</span>';
                                }            
                            }
                        }
                    ?>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()) :?>
                    <?php foreach ($messages as $message) :?>
                        <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) :?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>

        <?php if ($canApplyMsrp) :?>
            <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            </td>
        <?php else :?>
            <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td>
        <?php endif; ?>
        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
            <div class="field qty">
                <div class="control qty">
                    <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                        <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                        <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                               name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                               data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                               value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                               type="number"
                               size="4"
                               step="any"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"/>
                    </label>
                </div>
            </div>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp) :?>
                <span class="cart msrp subtotal">--</span>
            <?php else :?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        </td>
    </tr>
    <tr class="item-actions">
        <td colspan="4">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>
