<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $_item \Magento\Sales\Model\Order\Item */

$_item = $block->getItem();
$_order = $_item->getOrder();
$_store = $_order->getStore();


$_imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Image');
$_baseImageUrl = $_store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).'catalog/product';

?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <div class="image-description" style="display:flex; margin-right:10px">
        <img src="<?= $_imageHelper->init($_item->getProduct(), 'small_image', ['type'=>'small_image'])->keepAspectRatio(true)->resize('65','65')->getUrl();?>" alt="<?= __('Product Image');?>">
            <div class="article-description">
                <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
                <p class="sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
                <?php if ($block->getItemOptions()) : ?>
                    <dl class="item-options">
                        <?php foreach ($block->getItemOptions() as $option) : ?>
                            <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                            <dd>
                                <?= /* @noEscape */  nl2br($option['value']) ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) : ?>
                    <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
                <?php endif; ?>
                <?= $block->escapeHtml($_item->getDescription()) ?>
            </div>
        </div>
    </td>
    <td class="item-qty"><?= (float) $_item->getQty() ?></td>
</tr>
